// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by re-running the configuration.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOaZefTm1Zcmsc6OcQeWvR_eLMqj0Tdr8',
    appId: '1:814576249420:web:90cba9c1d6986f4c4c62e9',
    messagingSenderId: '814576249420',
    projectId: 'subscription-app-b67fb',
    authDomain: 'subscription-app-b67fb.firebaseapp.com',
    storageBucket: 'subscription-app-b67fb.firebasestorage.app',
    measurementId: 'G-NDCE8SBCE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArIN-0TJmjFWyZ0BbbqBhhesQB2yHJR6g',
    appId: '1:814576249420:android:e036752a0b03263f4c62e9',
    messagingSenderId: '814576249420',
    projectId: 'subscription-app-b67fb',
    storageBucket: 'subscription-app-b67fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw7YWa5rBpeLcpMUaiEetk-fzmRseIg1A', // Requires manual setup
    appId: '1:814576249420:ios:placeholder',
    messagingSenderId: '814576249420',
    projectId: 'subscription-app-b67fb',
    storageBucket: 'subscription-app-b67fb.firebasestorage.app',
    iosBundleId: 'com.example.p_v_j',
  );
}
